# Generated by Django 4.2.4 on 2023-08-24 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='certificate',
            field=models.ImageField(blank=True, null=True, upload_to='student/%Y/%m/%d'),
        ),
    ]
