# Generated by Django 4.2.4 on 2023-09-06 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0002_student_certificate'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='slug',
            field=models.SlugField(default=1),
            preserve_default=False,
        ),
    ]
