# Generated by Django 4.2.4 on 2023-09-06 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0004_course_mentor'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='certificates.course'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='mentor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='certificates.mentor'),
            preserve_default=False,
        ),
    ]
